apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elastic-agent-helm.fullname" . }}
  labels:
    {{- include "elastic-agent-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "elastic-agent-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elastic-agent-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FLEET_URL
              value: "{{ .Values.fleet.url }}"
            - name: FLEET_ENROLLMENT_TOKEN
              value: "{{ .Values.fleet.enrollmentToken }}"
            - name: FLEET_SERVER_POLICY_ID
              value: "{{ .Values.fleet.serverPolicyID }}"
            - name: KIBANA_HOST
              value: "{{ .Values.fleet.kibanaHost }}"
            - name: KIBANA_FLEET_USERNAME
              value: "{{ .Values.fleet.kibanaFleetUsername }}"
            - name: KIBANA_FLEET_PASSWORD
              value: "{{ .Values.fleet.kibanaFleetPassword }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

